if(EXISTS "/Users/yangyizhi/chps2023/TDs/TD2_5/b4/Test.exe[1]_tests.cmake")
  include("/Users/yangyizhi/chps2023/TDs/TD2_5/b4/Test.exe[1]_tests.cmake")
else()
  add_test(Test.exe_NOT_BUILT Test.exe_NOT_BUILT)
endif()
