image: timbru31/node-chrome:gallium
export:

  script:
    - npm install -g @marp-team/marp-cli
    - apt update
    - apt-get install libxss1
    - apt-get -y install pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra
    - pandoc prerequis.md -o prerequis.pdf
    - pandoc index.md -o index.pdf
    - pandoc detailed_index.md -o detailed_index.pdf
    - pandoc TDs/TD1_cmake.md -o TDs/TD1_cmake.pdf
    - pandoc TDs/TD2-5_intro.md -o TDs/TD2-5_intro.pdf
    - pandoc TDs/TD2_simulator_architecture.md -o TDs/TD2_simulator_architecture.pdf
    - pandoc TDs/TD3_equation_and_numerical_scheme.md -o TD3_equation_and_numerical_scheme.pdf
    - pandoc TDs/Help_install_gtest.md -o TDs/Help_install_gtest.pdf
    - marp intro.md --pdf
    - marp part1_survival_kit/part1_survival_kit-1_TooL.md --pdf
    - marp part1_survival_kit/part1_survival_kit-2_OO.md --pdf
    - marp part1_survival_kit/part1_survival_kit-3_Mem.md --pdf
    - marp part1_survival_kit/part1_survival_kit-4_Static.md --pdf
    - marp part2_deep_water/part2_deep_water-1_TooL.md --pdf
    - marp part2_deep_water/part2_deep_water-2_Mem.md --pdf   
    - marp part2_deep_water/part2_deep_water-3_OO.md --pdf
 
    


    
  
  artifacts:
    paths:
      - prerequis.pdf
      - index.pdf
      - detailed_index.pdf
      - intro.pdf
      - part1_survival_kit/part1_survival_kit-1_TooL.pdf
      - part1_survival_kit/part1_survival_kit-2_OO.pdf
      - part1_survival_kit/part1_survival_kit-3_Mem.pdf
      - part1_survival_kit/part1_survival_kit-4_Static.pdf
      - part2_deep_water/part2_deep_water-1_TooL.pdf
      - part2_deep_water/part2_deep_water-2_Mem.pdf
      - part2_deep_water/part2_deep_water-3_OO.pdf

      - TDs/TD1_cmake.pdf
      - TDs/Help_install_gtest.pdf
      - TDs/TD2-5_intro.pdf
      - TDs/TD2_simulator_architecture.pdf
      - TDs/TD3_equation_and_numerical_scheme.pdf
    
    untracked: false
    expire_in: 30 days
